### ISSUE TITLE
Clear old audiocache

### ISSUE THREAD

**Issue by MarcelloTheArcane** [MarcelloTheArcane/m#1]
Somehow need to free up space for garbage collection - these files get quite big.

Something like clearing past songs as long as they aren't in the future too. Not sure when to cycle it. Maybe dispatch after a play event.

**Comment by thetre97** [comment]
LRU Cache?

**Comment by MarcelloTheArcane** [comment]
@thetre97 A what?

**Comment by MarcelloTheArcane** [comment]
Tentatively reclosing
